; 6502js Simulator Download: https://github.com/skilldrick/6502js
; https://github.com/wynand1004/Projects/tree/master/6502_Demo

LDX #0      ; START WITH BLACK CURSOR COLOR

START:

RIGHT:
LDA $FF     ; LOAD VALUE FROM LOCATION FF (LAST KEYPRESS)
CMP #$64    ; COMPARE IF VALUE IN ACUMULATOR IS [d]key
BNE LEFT    ; BRANCH IF NOT EQUAL (IF NOT d THEN JUMP)
LDA #$00    ; IF d THEN LOAD ACUMULATOR
STA $200,X  ; STORE BLACK IN CURRENT SPOT
STA $FF     ; STORE ALSO IN FF
INX         ; INCREMENT X (WE WANT TO GO RIGHT)   
JMP DISPLAY

LEFT:
LDA $FF     ; LOAD VALUE FROM LOCATION FF (LAST KEYPRESS)
CMP #$61    ; COMPARE IF VALUE IN ACUMULATOR IS [a]key
BNE DISPLAY ; BRANCH IF NOT EQUAL (IF NOT a THEN JUMP)
LDA #$00    ; IF a THEN LOAD ACUMULATOR
STA $200,X  ; STORE BLACK IN CURRENT SPOT
STA $FF     ; STORE ALSO IN FF
DEX         ; DECREMENT X (WE WANT TO GO LEFT)   
JMP DISPLAY

DISPLAY:
LDA #$FE    ; LOAD A RANDOM COLOR FOR CURSOR
STA $200,X

JMP START